### ISSUE TITLE
FIO and SF failed to run

### ISSUE THREAD

**Issue by Avilir** [cloud-bulldozer/benchmark-wrapper#378]
The FIO and the SmallFiles benchmarks failed to run (same tests ran ok a week ago) with :
```
Traceback (most recent call last):
  File "/usr/local/bin/run_snafu", line 33, in <module>
    sys.exit(load_entry_point('snafu', 'console_scripts', 'run_snafu')())
  File "/usr/local/bin/run_snafu", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/snafu/snafu/run_snafu.py", line 37, in <module>
    from snafu.utils.wrapper_factory import wrapper_factory
  File "/opt/snafu/snafu/utils/wrapper_factory.py", line 10, in <module>
    from snafu.log_generator_wrapper.log_generator_wrapper import log_generator_wrapper
  File "/opt/snafu/snafu/log_generator_wrapper/log_generator_wrapper.py", line 17, in <module>
    from .trigger_log_generator import Trigger_log_generator
  File "/opt/snafu/snafu/log_generator_wrapper/trigger_log_generator.py", line 26, in <module>
    import boto3
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.6/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.6/site-packages/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.6/site-packages/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'PROTOCOL_TLS'
```

**Comment by chentex** [comment]
Thank you, a PR is in place for this https://github.com/cloud-bulldozer/benchmark-wrapper/pull/376

**Comment by jtaleric** [comment]
@Avilir can you confirm this is still a problem? @chentex fixed this with a PR yesterday : https://github.com/cloud-bulldozer/benchmark-wrapper/pull/380

**Comment by Avilir** [comment]
The small file is still crashing with the same error.
I am testing the FIO now and will update as well.

**Comment by Avilir** [comment]
FIO is working fine.

**Comment by chentex** [comment]
Do you have the `latest` tag for `smallfile`, I see it is passing the test

**Comment by Avilir** [comment]
I am cloning the benchmark-operator repo before each test and run it from there.
so if it have `latest` tag there, then i have it...

**Comment by chentex** [comment]
OK, I see the problem, `benchmark-operator` is using tag `master` and it is not updated, let me open a PR for that fix

**Comment by chentex** [comment]
PR: https://github.com/cloud-bulldozer/benchmark-operator/pull/711
