### ISSUE TITLE
uperf Docker Image creation fails on ppc64le

### ISSUE THREAD

**Issue by varad-ahirwadkar** [cloud-bulldozer/benchmark-wrapper#483]
Hi, I am trying to build uperf image for ppc64le architecture but it keeps failing.
Dockerfile: [Dockerfile.ppc64le](https://github.com/cloud-bulldozer/benchmark-wrapper/blob/master/snafu/benchmarks/uperf/Dockerfile.ppc64le)

```
20.56     Error compiling Cython file:                                                                                                                                                                        [37/292]
20.56     ------------------------------------------------------------
20.56     ...
20.56             for i in range(1, RK_STATE_LEN):
20.56                 self.rng_state.key[i] = val[i]
20.56             self.rng_state.pos = i
20.56
20.56             self._bitgen.state = &self.rng_state
20.56             self._bitgen.next_uint64 = &mt19937_uint64
20.56                                        ^
20.56     ------------------------------------------------------------
20.56
20.56     _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (vo
id *) except? -1 nogil'.
20.56     Processing numpy/random/_bounded_integers.pxd.in
20.56     Processing numpy/random/_mt19937.pyx
20.56     Traceback (most recent call last):
20.56       File "/tmp/pip-build-blhqmw4j/numpy/tools/cythonize.py", line 235, in <module>
20.56         main()
20.56       File "/tmp/pip-build-blhqmw4j/numpy/tools/cythonize.py", line 231, in main
20.56         find_process_files(root_dir)
20.56       File "/tmp/pip-build-blhqmw4j/numpy/tools/cythonize.py", line 222, in find_process_files
20.56         process(root_dir, fromfile, tofile, function, hash_db)
20.56       File "/tmp/pip-build-blhqmw4j/numpy/tools/cythonize.py", line 188, in process
20.56         processor_function(fromfile, tofile)
20.56       File "/tmp/pip-build-blhqmw4j/numpy/tools/cythonize.py", line 78, in process_pyx
20.56         [sys.executable, '-m', 'cython'] + flags + ["-o", tofile, fromfile])
20.56       File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
20.56         raise CalledProcessError(retcode, cmd)
20.56     subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
20.56     Traceback (most recent call last):
20.56       File "<string>", line 1, in <module>
20.56       File "/tmp/pip-build-blhqmw4j/numpy/setup.py", line 508, in <module>
20.56         setup_package()
20.56       File "/tmp/pip-build-blhqmw4j/numpy/setup.py", line 488, in setup_package
20.56         generate_cython()
20.56       File "/tmp/pip-build-blhqmw4j/numpy/setup.py", line 285, in generate_cython
20.56         raise RuntimeError("Running cythonize failed!")
20.56     RuntimeError: Running cythonize failed!
20.56
20.56     ----------------------------------------
20.81 Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-blhqmw4j/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(co
mpile(code, __file__, 'exec'))" install --record /tmp/pip-d4559aoh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-blhqmw4j/numpy/
------
Dockerfile.ppc64le:9
--------------------
   7 |     RUN dnf install -y uperf && dnf clean all
   8 |     RUN ln -s /usr/bin/python3 /usr/bin/python
   9 | >>> RUN python3 -m pip install --upgrade cython numpy importlib_metadata 'urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1' && python3 -m pip install --upgrade scipy pandas
  10 |     RUN mkdir -p /opt/snafu/
  11 |     COPY . /opt/snafu/
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m pip install --upgrade cython numpy importlib_metadata 'urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1' && python3 -m pip install --upgrade scipy pandas" did not compl
ete successfully: exit code: 1
```

**Comment by krishvoor** [comment]
Hi @varad-ahirwadkar 👋 
I have had conversations with Kishen Viswanathan from the OCP-ppc64le team.
I understand you are attempting network testing on Multi-arch OCP 4.15 - we have some data-path tests:

1) https://github.com/cloud-bulldozer/k8s-netperf
2) https://github.com/cloud-bulldozer/ingress-perf

These are written in Go-lang and you can get started on them really quickly
Please let me know in case you need more information would be happy to help

**Comment by varad-ahirwadkar** [comment]
Hi @krishvoor,
Thanks I will use these.

**Comment by krishvoor** [comment]
Incase you need more information please reach out to us.
I will close this issue.
